MODEL:
  NUM_CLASSES: 2
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("polyp_train", "polyp_val")
  TEST: ("polyp_test", )
SOLVER:
  MAX_ITER: 120000
  LR_STEPS: [80000, 100000]
  GAMMA: 0.1
  BATCH_SIZE: 32
  LR: 1e-4

OUTPUT_DIR: 'outputs/vgg_ssd300_publicpolyp'