MODEL:
  NUM_CLASSES: 2
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("polyp_train", ) # 训练集
  # TEST: ("polyp_val", ) # 训练时用这个当作验证集，测试时注释掉这一行，
  TEST: ("polyp_test", ) # 测试时用这一行，test.py测试时会调用到作为test_loader

SOLVER:
  MAX_ITER: 120000
  LR_STEPS: [80000, 100000]
  GAMMA: 0.1
  BATCH_SIZE: 32
  LR: 1e-4

# OUTPUT_DIR: 'outputs/vgg_ssd300_publicpolyp'
# OUTPUT_DIR: 'outputs/lrud_vgg_ssd300_publicpolyp'
OUTPUT_DIR: 'outputs/debug'
